Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.network "public_network", ip: "192.168.0.160", bridge: "wlp2s0"
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntu.vm.synced_folder "./configs", "/configs"

    ubuntu.vm.provision "shell", inline: <<-SHELL
      cat /configs/authorized_keys >> .ssh/authorized_keys
    SHELL
  end

  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.network "public_network", ip: "192.168.0.161", bridge: "wlp2s0"
    ubuntu2.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntu2.vm.synced_folder "./configs", "/configs"

    ubuntu2.vm.provision "shell", inline: <<-SHELL
      cat /configs/authorized_keys >> .ssh/authorized_keys
    SHELL
  end
end